version: 0.2
phases:
  build:
    commands:
      - aws s3 sync . s3://$BUCKET_NAME --exclude "*" --include "*.html" --include "*.css" --include "app.js" --include "logo.jpg"
      - DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '$BUCKET_NAME')].Id" --output text)
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*" || true