version: 0.2
phases:
  build:
    commands:
      - aws s3 sync . s3://web3-prod-app-540257590858-us-west-2 --exclude "*" --include "*.html" --include "*.css" --include "app.js" --include "logo.jpg"
      - DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, 'web3-prod-app-540257590858-us-west-2')].Id" --output text)
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*" || true